version: '3.8'
services:
  db:
    container_name: postgres-db
    image: postgres:16.1
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
