<script setup lang="ts">
definePageMeta({
  middleware: ['auth-admin'],
})
</script>

<template>
  <div class="p-4">
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
    <h1>Admin Page</h1>
  </div>
</template>
